In [112]:
import pandas as pd
import geopandas as gpd
import numpy as np
from scipy.spatial import cKDTree
import re
import os
import time
import requests
from dotenv import load_dotenv

Data Validation Utility

In [61]:
def validate_geodataframe(gdf, name="GeoDataFrame"):
    """
    Validate a GeoDataFrame before analysis.
    Checks for null geometries, invalid geometries, and CRS information.
    Optionally auto-fixes invalid geometries using buffer(0).
    
    Parameters:
    -----------
    gdf : geopandas.GeoDataFrame
        The GeoDataFrame to validate
    name : str
        A descriptive name for the dataset (used in print output)
    
    Returns:
    --------
    geopandas.GeoDataFrame
        The validated (and potentially fixed) GeoDataFrame
    """
    print(f"Validating '{name}'...")
    print(f"  - Total records: {len(gdf)}")
    print(f"  - CRS: {gdf.crs}")
    
    null_count = gdf.geometry.isnull().sum()
    invalid_count = (~gdf.geometry.is_valid).sum()
    
    print(f"  - Null geometries: {null_count}")
    print(f"  - Invalid geometries: {invalid_count}")
    
    if null_count > 0:
        print(f"  WARNING: Contains {null_count} null geometries - these rows may cause issues in spatial operations")
    
    if invalid_count > 0:
        print(f"  WARNING: Contains {invalid_count} invalid geometries - attempting to fix with buffer(0)...")
        gdf = gdf.copy()
        gdf['geometry'] = gdf.geometry.buffer(0)
        new_invalid_count = (~gdf.geometry.is_valid).sum()
        if new_invalid_count == 0:
            print(f"  SUCCESS: All geometries are now valid")
        else:
            print(f"  PARTIAL FIX: {new_invalid_count} geometries still invalid")
    
    print(f"  Validation complete.\n")
    return gdf

### 1. HDB resale price with coordinates

1.1 HDB resale price 2025

In [62]:
resale_price_df =  pd.read_csv("../datasets/Resale flat prices based on registration date from Jan-2017 onwards.csv")

In [63]:
def clean_street_name(street):
    if pd.isna(street): return street
    street = street.upper().strip()
    
    # Define common Singapore address abbreviations
    replacements = {
        r'\bBT\b': 'BUKIT',
        r'\bRD\b': 'ROAD',
        r'\bAVE\b': 'AVENUE',
        r'\bDR\b': 'DRIVE',
        r'\bCL\b': 'CLOSE',
        r'\bCTRL\b': 'CENTRAL',
        r'\bCPD\b': 'COMPOUND',
        r'\bCRES\b': 'CRESCENT',
        r'\bGRV\b': 'GROVE',
        r'\bHWY\b': 'HIGHWAY',
        r'\bJLN\b': 'JALAN',
        r'\bKG\b': 'KAMPONG',
        r'\bLN\b': 'LANE', 
        r'\bMT\b': 'MOUNT',
        r'\bPL\b': 'PLACE',
        r'\bRS\b': 'RISE',
        r'\bTER\b': 'TERRACE',
        r'\bTG\b': 'TANJONG',
        r'\bUPP\b': 'UPPER',
        r'\bNTH\b': 'NORTH',
        r'\bSTH\b': 'SOUTH',
        r'\bPK\b': 'PARK',
        r'\bMKT\b': 'MARKET',
        r"\bC'WEALTH\b": 'COMMONWEALTH',
        r"\bLOR\b": 'LORONG',
        r'\bHTS\b': 'HEIGHTS',
        r'\bGDNS\b': 'GARDENS',
        r'\bST\b(?!\.)': 'STREET'
    }
    
    for short, full in replacements.items():
        street = re.sub(short, full, street)
    
    # Remove extra spaces caused by regex
    return " ".join(street.split())

In [64]:
# filter only 2019-2025 resale data 
resale_price_df["month"]= pd.to_datetime(resale_price_df["month"])
resale_df = resale_price_df[(resale_price_df["month"].dt.year >= 2019) & (resale_price_df["month"].dt.year <= 2025)].copy()
resale_df['street_name'] = resale_df['street_name'].apply(clean_street_name)

# create year and month columns 
resale_df['year'] = resale_df['month'].dt.year
resale_df['month'] = resale_df['month'].dt.month
resale_df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,year
42070,1,ANG MO KIO,3 ROOM,225,ANG MO KIO AVENUE 1,01 TO 03,67.0,New Generation,1978,58 years,230000.0,2019
42071,1,ANG MO KIO,3 ROOM,174,ANG MO KIO AVENUE 4,01 TO 03,60.0,Improved,1986,66 years,235000.0,2019
42072,1,ANG MO KIO,3 ROOM,440,ANG MO KIO AVENUE 10,04 TO 06,67.0,New Generation,1979,59 years,238000.0,2019
42073,1,ANG MO KIO,3 ROOM,174,ANG MO KIO AVENUE 4,10 TO 12,61.0,Improved,1986,66 years 01 month,240000.0,2019
42074,1,ANG MO KIO,3 ROOM,637,ANG MO KIO AVENUE 6,01 TO 03,68.0,New Generation,1980,60 years 08 months,240000.0,2019

1.2 Existing HDBs

In [140]:
# Instead of scraping from OneMap, we can use the HDB Existing Building dataset which contains the coordinates for all HDB blocks. 
# We will match on block and street name to get the coordinates for each resale transaction.
hdb_existing = gpd.read_file("../datasets/HDBExistingBuilding.geojson")
road_namecode = pd.read_excel("../datasets/road_name_code.xlsx", skiprows= 10)

In [141]:
road_namecode = road_namecode[["Domain Value", "Description"]].copy()

# match on "ST_COD" = "Domain Value" to get road description
hdb_existing = hdb_existing.merge(
    road_namecode,
    left_on= "ST_COD", 
    right_on= "Domain Value", 
    how= "left"
)
# ensure all ST_COD has a match
unmatched_rows = hdb_existing[hdb_existing['Domain Value'].isna()]
if unmatched_rows.empty:
    print("All 'ST_COD' values found a match in the road name table.")
else:
    print(f"{len(unmatched_rows)} rows failed to match.")
    print("Missing ST_COD values:")
    print(unmatched_rows['ST_COD'].unique())
    
# rename and select columns
hdb_existing = hdb_existing.rename(columns={"Description": "STREET_NAME", "geometry": "GEOMETRY"})
hdb_existing = hdb_existing[["BLK_NO", "STREET_NAME", "GEOMETRY", "POSTAL_COD"]]
hdb_existing.head()

All 'ST_COD' values found a match in the road name table.

,BLK_NO,STREET_NAME,GEOMETRY,POSTAL_COD
0,208B,CLEMENTI AVENUE 6,"POLYGON ((103.76235 1.32274, 103.76232 1.32274...",122208
1,238,BUKIT BATOK EAST AVENUE 5,"POLYGON ((103.75446 1.3501, 103.75448 1.35011,...",650238
2,88,CIRCUIT ROAD,"POLYGON ((103.88589 1.32371, 103.88579 1.3237,...",370088
3,44A,MARINE CRESCENT,"POLYGON ((103.91325 1.30501, 103.91325 1.30503...",441044
4,671B,JURONG WEST STREET 65,"POLYGON ((103.70208 1.34397, 103.70208 1.34398...",642671

1.3 Merge existing HDBs geometry with resale prices

In [142]:
# standardize to string types
resale_df['block'] = resale_df['block'].astype(str).str.strip()
hdb_existing['BLK_NO'] = hdb_existing['BLK_NO'].astype(str).str.strip()
# match on block and street name to get coordinates
resale_with_geom_df = resale_df.merge(
    hdb_existing, 
    left_on=['block', 'street_name'], 
    right_on=['BLK_NO', 'STREET_NAME'], 
    how='left'
)
# rename and select columns
resale_with_geom_df = resale_with_geom_df.rename(columns={'GEOMETRY': 'geometry', 'POSTAL_COD': 'postal_code'})
selected_columns = [
    'month', 
    'year',
    'town', 
    'flat_type', 
    'block', 
    'street_name', 
    'storey_range', 
    'floor_area_sqm', 
    'flat_model', 
    'lease_commence_date', 
    'remaining_lease', 
    'resale_price', 
    'geometry',
    'postal_code'
]
resale_with_geom_df = resale_with_geom_df[selected_columns]
# add address_cleaned column by concatenating block, street name
resale_with_geom_df.head()
resale_with_geom_df['address_clean'] = resale_with_geom_df['block'] + " "+ resale_with_geom_df['street_name']

In [163]:
# convert dataframe to geodataframe
resale_gdf = gpd.GeoDataFrame(resale_with_geom_df, geometry='geometry')
# reproject from geographic CRS (WGS84) to a projected CRS using EPSG:3414 (SVY21)
resale_gdf = resale_gdf.to_crs(3414)
# convert hdb polygons to points (centroids)
resale_gdf['geometry'] = resale_gdf['geometry'].centroid
resale_gdf.to_file("resale_2019_to_2025_cleaned.geojson", driver="GeoJSON")
resale_gdf.head(5)

,month,year,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,geometry,postal_code,address_clean
0,1,2019,ANG MO KIO,3 ROOM,225,ANG MO KIO AVENUE 1,01 TO 03,67.0,New Generation,1978,58 years,230000.0,POINT (28537.68 38825.233),560225,225 ANG MO KIO AVENUE 1
1,1,2019,ANG MO KIO,3 ROOM,174,ANG MO KIO AVENUE 4,01 TO 03,60.0,Improved,1986,66 years,235000.0,POINT (28487.136 39687.765),560174,174 ANG MO KIO AVENUE 4
2,1,2019,ANG MO KIO,3 ROOM,440,ANG MO KIO AVENUE 10,04 TO 06,67.0,New Generation,1979,59 years,238000.0,POINT (30336.26 38718.18),560440,440 ANG MO KIO AVENUE 10
3,1,2019,ANG MO KIO,3 ROOM,174,ANG MO KIO AVENUE 4,10 TO 12,61.0,Improved,1986,66 years 01 month,240000.0,POINT (28487.136 39687.765),560174,174 ANG MO KIO AVENUE 4
4,1,2019,ANG MO KIO,3 ROOM,637,ANG MO KIO AVENUE 6,01 TO 03,68.0,New Generation,1980,60 years 08 months,240000.0,POINT (29003.603 40255.313),560637,637 ANG MO KIO AVENUE 6

### 2. Get school coordinates using OneMap API

In [ ]:
## Get centroid coordinates for schools using OneMap API
df = pd.read_csv("../school_scoring/schools_tiered.csv")

# output columns
for col in ["latitude", "longitude", "searchval", "formatted_address", "postal_found", "geocode_status", "matched_query"]:
    if col not in df.columns:
        df[col] = None

# import request
base_url = "https://www.onemap.gov.sg/api/common/elastic/search"

count = 0

for i in range(len(df)):
    if pd.notna(df.loc[i, "latitude"]) and pd.notna(df.loc[i, "longitude"]):
        print(f"Row {i}: already geocoded")
        continue

    school_name = str(df.loc[i, "school_name"]).strip() if pd.notna(df.loc[i, "school_name"]) else ""
    address = str(df.loc[i, "address"]).strip() if pd.notna(df.loc[i, "address"]) else ""
    postal_code = str(df.loc[i, "postal_code"]).strip() if pd.notna(df.loc[i, "postal_code"]) else ""

    queries = []

    if postal_code and postal_code.lower() != "nan":
        queries.append(("postal_code", postal_code))

    if address and address.lower() != "nan":
        queries.append(("address", f"{address} Singapore"))

    if school_name and school_name.lower() != "nan":
        queries.append(("school_name", school_name))

    result = None
    matched_query_type = None

    try:
        for query_type, q in queries:
            params = {
                "searchVal": q,
                "returnGeom": "Y",
                "getAddrDetails": "Y",
                "pageNum": 1
            }

            resp = requests.get(base_url, params=params, timeout=15)
            time.sleep(0.5)
            resp.raise_for_status()
            data = resp.json()

            if data.get("results") and len(data["results"]) > 0:
                result = data["results"][0]
                matched_query_type = query_type
                break

        if result is not None:
            df.loc[i, "longitude"] = result.get("LONGITUDE")
            df.loc[i, "latitude"] = result.get("LATITUDE")
            df.loc[i, "searchval"] = result.get("SEARCHVAL")
            df.loc[i, "formatted_address"] = result.get("ADDRESS")
            df.loc[i, "postal_found"] = result.get("POSTAL")
            df.loc[i, "geocode_status"] = "success"
            df.loc[i, "matched_query"] = matched_query_type

            print(
                f"{school_name}: success via {matched_query_type} | "
                f"lat={result.get('LATITUDE')}, lon={result.get('LONGITUDE')}"
            )
        else:
            df.loc[i, "geocode_status"] = "not_found"
            df.loc[i, "matched_query"] = None
            print(f"{school_name}: not found")

    except Exception as e:
        df.loc[i, "geocode_status"] = f"error: {str(e)}"
        df.loc[i, "matched_query"] = None
        print(f"{school_name}: error -> {e}")

    count += 1

    if count % 50 == 0:
        df.to_csv("schools_geocoded_partial.csv", index=False)
        print(f"Saved partial progress at row {i}. Sleeping for 2 seconds...")
        time.sleep(2)

# df.to_csv("schools_geocoded.csv", index=False)
schools_gdf = df
print("Done.")

NANYANG PRIMARY SCHOOL: success via postal_code | lat=1.321070942411543, lon=103.8076818527984
CATHOLIC HIGH SCHOOL: success via postal_code | lat=1.354525170657562, lon=103.8449008048039
CHIJ ST. NICHOLAS GIRLS' SCHOOL: success via postal_code | lat=1.373476878789176, lon=103.8342532694353
TAO NAN SCHOOL: success via postal_code | lat=1.305285286873217, lon=103.9115531523253
NAN HUA PRIMARY SCHOOL: success via postal_code | lat=1.319201599563877, lon=103.7610950657604
AI TONG SCHOOL: success via postal_code | lat=1.360583433890406, lon=103.8330203339857
ANGLO-CHINESE SCHOOL (PRIMARY): success via postal_code | lat=1.31837054523522, lon=103.8356097323541
MARIS STELLA HIGH SCHOOL: success via postal_code | lat=1.34139181236128, lon=103.8777407134485
ROSYTH SCHOOL: success via postal_code | lat=1.372858365405815, lon=103.8747717039899
HOLY INNOCENTS' PRIMARY SCHOOL: success via postal_code | lat=1.366938308773486, lon=103.8941148997942
PEI HWA PRESBYTERIAN PRIMARY SCHOOL: success via postal_code | lat=1.338073021211523, lon=103.7762509030947
HENRY PARK PRIMARY SCHOOL: success via postal_code | lat=1.316676461783479, lon=103.7842962277468
METHODIST GIRLS' SCHOOL (PRIMARY): success via postal_code | lat=1.332662135996364, lon=103.7833821140175
MAHA BODHI SCHOOL: success via postal_code | lat=1.328580238735551, lon=103.9013069041567
ST. HILDA'S PRIMARY SCHOOL: success via postal_code | lat=1.349679789698374, lon=103.937016363397
KONG HWA SCHOOL: success via postal_code | lat=1.310996740091935, lon=103.8883520290672
RED SWASTIKA SCHOOL: success via postal_code | lat=1.334056595808593, lon=103.9343175284833
SINGAPORE CHINESE GIRLS' PRIMARY SCHOOL: success via postal_code | lat=1.320634083518409, lon=103.8281649669527
PEI CHUN PUBLIC SCHOOL: success via postal_code | lat=1.336778643906726, lon=103.8553413102114
RAFFLES GIRLS' PRIMARY SCHOOL: success via postal_code | lat=1.330041780682768, lon=103.8063978289381
ANGLO-CHINESE SCHOOL (JUNIOR): success via postal_code | lat=1.309350412749673, lon=103.840950265464
POI CHING SCHOOL: success via postal_code | lat=1.357651218776781, lon=103.9352464861737
HONG WEN SCHOOL: success via postal_code | lat=1.321759999645534, lon=103.8576284688807
NAN CHIAU PRIMARY SCHOOL: success via postal_code | lat=1.392211499065922, lon=103.8911809281855
PRINCESS ELIZABETH PRIMARY SCHOOL: success via postal_code | lat=1.349190988575864, lon=103.7407192080109
FAIRFIELD METHODIST SCHOOL (PRIMARY): success via postal_code | lat=1.301004419167346, lon=103.785455606827
SOUTH VIEW PRIMARY SCHOOL: success via postal_code | lat=1.381431239876985, lon=103.7471536709992
CHONGFU SCHOOL: success via postal_code | lat=1.438395628970071, lon=103.8393091738164
CHIJ PRIMARY (TOA PAYOH): success via postal_code | lat=1.332752647115879, lon=103.8418472637856
ST. JOSEPH'S INSTITUTION JUNIOR: success via postal_code | lat=1.317814761185532, lon=103.8456333345214
RULANG PRIMARY SCHOOL: success via postal_code | lat=1.346738688890966, lon=103.7184579554868
KUO CHUAN PRESBYTERIAN PRIMARY SCHOOL: success via postal_code | lat=1.349398136695366, lon=103.8550182333104
NORTHLAND PRIMARY SCHOOL: success via postal_code | lat=1.421304041598082, lon=103.8407929233448
ST. ANTHONY'S PRIMARY SCHOOL: success via postal_code | lat=1.364119484758337, lon=103.7492519190488
GONGSHANG PRIMARY SCHOOL: success via postal_code | lat=1.357116067902936, lon=103.9491447972771
ADMIRALTY PRIMARY SCHOOL: success via postal_code | lat=1.442634790331114, lon=103.800040119743
MEE TOH SCHOOL: success via postal_code | lat=1.394853560818655, lon=103.90857257736
SHUQUN PRIMARY SCHOOL: success via postal_code | lat=1.346869672590671, lon=103.7215593872028
SENGKANG GREEN PRIMARY SCHOOL: success via postal_code | lat=1.392540093081118, lon=103.8749848695505
BUKIT PANJANG PRIMARY SCHOOL: success via postal_code | lat=1.373500899865845, lon=103.7694173376537
TEMASEK PRIMARY SCHOOL: success via postal_code | lat=1.317203416630649, lon=103.9457594378398
PAYA LEBAR METHODIST GIRLS' SCHOOL (PRIMARY): success via postal_code | lat=1.350254560089406, lon=103.8848468761118
ANDERSON PRIMARY SCHOOL: success via postal_code | lat=1.384199419079249, lon=103.8414117160062
RADIN MAS PRIMARY SCHOOL: success via postal_code | lat=1.274897015297713, lon=103.8241157816578
XINMIN PRIMARY SCHOOL: success via postal_code | lat=1.371767983174687, lon=103.8828099178501
WELLINGTON PRIMARY SCHOOL: success via postal_code | lat=1.451685176147782, lon=103.8225162080872
FRONTIER PRIMARY SCHOOL: success via postal_code | lat=1.336412987432344, lon=103.6997017393095
PASIR RIS PRIMARY SCHOOL: success via postal_code | lat=1.372451327220885, lon=103.9629226990302
YANGZHENG PRIMARY SCHOOL: success via postal_code | lat=1.348976808384122, lon=103.8684671299535
ST. ANDREW'S JUNIOR SCHOOL: success via postal_code | lat=1.331402553088687, lon=103.8651171343844
Saved partial progress at row 49. Sleeping for 2 seconds...
HORIZON PRIMARY SCHOOL: success via postal_code | lat=1.399550034492005, lon=103.9134048556651
DE LA SALLE SCHOOL: success via postal_code | lat=1.394707829639912, lon=103.7432018128305
YU NENG PRIMARY SCHOOL: success via postal_code | lat=1.333980378940721, lon=103.9320150362959
KEMING PRIMARY SCHOOL: success via postal_code | lat=1.345528499608757, lon=103.7564493993506
WESTWOOD PRIMARY SCHOOL: success via postal_code | lat=1.347710965472197, lon=103.7004675207911
HOUGANG PRIMARY SCHOOL: success via postal_code | lat=1.377382452314626, lon=103.8808052745566
RIVER VALLEY PRIMARY SCHOOL: success via postal_code | lat=1.294183478428372, lon=103.8360189415711
WOODLANDS PRIMARY SCHOOL: success via postal_code | lat=1.436582707202003, lon=103.791791282236
ST. GABRIEL'S PRIMARY SCHOOL: success via postal_code | lat=1.349307667955572, lon=103.8623098999852
CHIJ OUR LADY OF THE NATIVITY: success via postal_code | lat=1.373302971401289, lon=103.8975757283031
NGEE ANN PRIMARY SCHOOL: success via postal_code | lat=1.305532241804384, lon=103.917570005713
HUAMIN PRIMARY SCHOOL: success via postal_code | lat=1.426972845129362, lon=103.8442402265639
PUNGGOL GREEN PRIMARY SCHOOL: success via postal_code | lat=1.401725904505284, lon=103.8987942623066
CHUA CHU KANG PRIMARY SCHOOL: success via postal_code | lat=1.377758900933685, lon=103.7418329174204
TANJONG KATONG PRIMARY SCHOOL: success via postal_code | lat=1.304984890448227, lon=103.8999999654065
CHONGZHENG PRIMARY SCHOOL: success via postal_code | lat=1.350611305685559, lon=103.9513172975512
RIVERSIDE PRIMARY SCHOOL: success via postal_code | lat=1.447004264937856, lon=103.8018890313332
GEYLANG METHODIST SCHOOL (PRIMARY): success via postal_code | lat=1.318144168273754, lon=103.8836285016008
CANBERRA PRIMARY SCHOOL: success via postal_code | lat=1.451250243715436, lon=103.8158588589283
NAVAL BASE PRIMARY SCHOOL: success via postal_code | lat=1.415901956976501, lon=103.8391005902065
ST. STEPHEN'S SCHOOL: success via postal_code | lat=1.318789972951361, lon=103.9172581295975
FENGSHAN PRIMARY SCHOOL: success via postal_code | lat=1.32980598760785, lon=103.9317102930578
RIVERVALE PRIMARY SCHOOL: success via postal_code | lat=1.393335062982132, lon=103.9045452532879
VALOUR PRIMARY SCHOOL: success via postal_code | lat=1.407441681637779, lon=103.8987621736618
WOODGROVE PRIMARY SCHOOL: success via postal_code | lat=1.432736207250495, lon=103.7902303139194
CHIJ (KELLOCK): success via postal_code | lat=1.275022722964019, lon=103.8281575648959
QIFA PRIMARY SCHOOL: success via postal_code | lat=1.313265832680701, lon=103.7566291018106
PUNGGOL PRIMARY SCHOOL: success via postal_code | lat=1.378200625476397, lon=103.8946671595121
CHIJ (KATONG) PRIMARY: success via postal_code | lat=1.306485352770875, lon=103.9111056204962
CANOSSA CATHOLIC PRIMARY SCHOOL: success via postal_code | lat=1.326644245448396, lon=103.8822279648518
ALEXANDRA PRIMARY SCHOOL: success via postal_code | lat=1.291334391613348, lon=103.8244246805311
COMPASSVALE PRIMARY SCHOOL: success via postal_code | lat=1.394445296365664, lon=103.8978122299046
NORTH VIEW PRIMARY SCHOOL: success via postal_code | lat=1.427451594625655, lon=103.8483784428927
WEST SPRING PRIMARY SCHOOL: success via postal_code | lat=1.389179718084546, lon=103.7663977228801
FUHUA PRIMARY SCHOOL: success via postal_code | lat=1.336597264658171, lon=103.7360894818831
TELOK KURAU PRIMARY SCHOOL: success via postal_code | lat=1.331096110019328, lon=103.9110053458552
CHIJ OUR LADY OF GOOD COUNSEL: success via postal_code | lat=1.357429522696155, lon=103.8640093973725
OASIS PRIMARY SCHOOL: success via postal_code | lat=1.405071847585848, lon=103.9112001938345
SEMBAWANG PRIMARY SCHOOL: success via postal_code | lat=1.445745309602403, lon=103.8211526762143
CHIJ OUR LADY QUEEN OF PEACE: success via postal_code | lat=1.366603668560997, lon=103.7674122046017
WATERWAY PRIMARY SCHOOL: success via postal_code | lat=1.398892612263155, lon=103.9185859245818
ANGSANA PRIMARY SCHOOL: success via postal_code | lat=1.363605905883133, lon=103.9389409003993
GREENRIDGE PRIMARY SCHOOL: success via postal_code | lat=1.385889219369218, lon=103.7677944692579
NORTH VISTA PRIMARY SCHOOL: success via postal_code | lat=1.382550661711514, lon=103.8962645754801
JING SHAN PRIMARY SCHOOL: success via postal_code | lat=1.371964457201105, lon=103.8517635316804
ZHENGHUA PRIMARY SCHOOL: success via postal_code | lat=1.379428736170532, lon=103.7697031720097
ELIAS PARK PRIMARY SCHOOL: success via postal_code | lat=1.375056963158182, lon=103.9452894168725
WEST GROVE PRIMARY SCHOOL: success via postal_code | lat=1.344712117689155, lon=103.6989642129882
ST. MARGARET'S SCHOOL (PRIMARY): success via postal_code | lat=1.304144073583324, lon=103.845820266438
QUEENSTOWN PRIMARY SCHOOL: success via postal_code | lat=1.295529055877536, lon=103.8076484756559
Saved partial progress at row 99. Sleeping for 2 seconds...
HAIG GIRLS' SCHOOL: success via postal_code | lat=1.311943442713839, lon=103.9029025571947
WHITE SANDS PRIMARY SCHOOL: success via postal_code | lat=1.365636109416956, lon=103.9608618146777
CASUARINA PRIMARY SCHOOL: success via postal_code | lat=1.372460639280005, lon=103.9570202861143
FERN GREEN PRIMARY SCHOOL: success via postal_code | lat=1.397269660504794, lon=103.8803303056833
MAYFLOWER PRIMARY SCHOOL: success via postal_code | lat=1.376376835476832, lon=103.8432528037418
JURONG WEST PRIMARY SCHOOL: success via postal_code | lat=1.33917519796104, lon=103.6988037322437
SPRINGDALE PRIMARY SCHOOL: success via postal_code | lat=1.395285444633771, lon=103.8894164135011
INNOVA PRIMARY SCHOOL: success via postal_code | lat=1.42896700684852, lon=103.7906075391852
JUNYUAN PRIMARY SCHOOL: success via postal_code | lat=1.347870747667462, lon=103.9392217090732
XISHAN PRIMARY SCHOOL: success via postal_code | lat=1.433471869250645, lon=103.8377553194475
TECK GHEE PRIMARY SCHOOL: success via postal_code | lat=1.365650185469026, lon=103.8510098004526
ST. ANTHONY'S CANOSSIAN PRIMARY SCHOOL: success via postal_code | lat=1.33472537301891, lon=103.9412348682017
QIHUA PRIMARY SCHOOL: success via postal_code | lat=1.442035965575938, lon=103.7883397620653
TAMPINES PRIMARY SCHOOL: success via postal_code | lat=1.350486394669401, lon=103.9435730985091
PUNGGOL VIEW PRIMARY SCHOOL: success via postal_code | lat=1.405052502260583, lon=103.9052990265681
XINGNAN PRIMARY SCHOOL: success via postal_code | lat=1.342706396692246, lon=103.6875884786809
WOODLANDS RING PRIMARY SCHOOL: success via postal_code | lat=1.434851793802362, lon=103.7974143435101
KHENG CHENG SCHOOL: success via postal_code | lat=1.337338193563907, lon=103.8471485018234
GREENWOOD PRIMARY SCHOOL: success via postal_code | lat=1.439899583317834, lon=103.8047255873839
MARSILING PRIMARY SCHOOL: success via postal_code | lat=1.43383904037059, lon=103.7736430138458
GREENDALE PRIMARY SCHOOL: success via postal_code | lat=1.39648195114255, lon=103.9123346207095
CORPORATION PRIMARY SCHOOL: success via postal_code | lat=1.351485487726621, lon=103.7075784049433
ANG MO KIO PRIMARY SCHOOL: success via postal_code | lat=1.369321765846087, lon=103.839630858752
NORTH SPRING PRIMARY SCHOOL: success via postal_code | lat=1.387061464948597, lon=103.9032026830277
UNITY PRIMARY SCHOOL: success via postal_code | lat=1.402783032190362, lon=103.7468012339729
MONTFORT JUNIOR SCHOOL: success via postal_code | lat=1.373624452340824, lon=103.8897414579003
ENDEAVOUR PRIMARY SCHOOL: success via postal_code | lat=1.453881704172645, lon=103.8171747016388
CLEMENTI PRIMARY SCHOOL: success via postal_code | lat=1.315063218278743, lon=103.7631444936865
PEIYING PRIMARY SCHOOL: success via postal_code | lat=1.417416275512517, lon=103.8301432098749
YISHUN PRIMARY SCHOOL: success via postal_code | lat=1.43397617334964, lon=103.8340507966576
JIEMIN PRIMARY SCHOOL: success via postal_code | lat=1.427688476652264, lon=103.8304254900925
LAKESIDE PRIMARY SCHOOL: success via postal_code | lat=1.338203977042863, lon=103.718089546664
FARRER PARK PRIMARY SCHOOL: success via postal_code | lat=1.312368676813718, lon=103.8507664029651
YEW TEE PRIMARY SCHOOL: success via postal_code | lat=1.396726034971953, lon=103.7518179929614
BUKIT TIMAH PRIMARY SCHOOL: success via postal_code | lat=1.33774986225881, lon=103.7668553447784
PARK VIEW PRIMARY SCHOOL: success via postal_code | lat=1.37801687647812, lon=103.9392021806994
OPERA ESTATE PRIMARY SCHOOL: success via postal_code | lat=1.319968763777494, lon=103.9237526686315
WEST VIEW PRIMARY SCHOOL: success via postal_code | lat=1.383785465462291, lon=103.7602734322579
FERNVALE PRIMARY SCHOOL: success via postal_code | lat=1.390302279637964, lon=103.874445458032
YIO CHU KANG PRIMARY SCHOOL: success via postal_code | lat=1.37793264345277, lon=103.885643682171
GAN ENG SENG PRIMARY SCHOOL: success via postal_code | lat=1.285595164949621, lon=103.8155474100632
PUNGGOL COVE PRIMARY SCHOOL: success via postal_code | lat=1.411584555624553, lon=103.89890448429
NORTHSHORE PRIMARY SCHOOL: success via postal_code | lat=1.418423220793498, lon=103.9051472011631
PEI TONG PRIMARY SCHOOL: success via postal_code | lat=1.31666529308968, lon=103.7674389995323
EVERGREEN PRIMARY SCHOOL: success via postal_code | lat=1.444148354515854, lon=103.7945452959214
YUHUA PRIMARY SCHOOL: success via postal_code | lat=1.342919816220172, lon=103.7408611488789
FUCHUN PRIMARY SCHOOL: success via postal_code | lat=1.430479908101254, lon=103.7781929442981
DAMAI PRIMARY SCHOOL: success via postal_code | lat=1.335246028297487, lon=103.9212864353203
BOON LAY GARDEN PRIMARY SCHOOL: success via postal_code | lat=1.342840137916176, lon=103.7128583819372
ZHANGDE PRIMARY SCHOOL: success via postal_code | lat=1.284211538554757, lon=103.8259518846363
Saved partial progress at row 149. Sleeping for 2 seconds...
TAMPINES NORTH PRIMARY SCHOOL: success via postal_code | lat=1.360487860256083, lon=103.9487689005172
CEDAR PRIMARY SCHOOL: success via postal_code | lat=1.335660843562641, lon=103.8756200625899
BUKIT VIEW PRIMARY SCHOOL: success via postal_code | lat=1.345860547886968, lon=103.75366641455
TOWNSVILLE PRIMARY SCHOOL: success via postal_code | lat=1.359946494775676, lon=103.8537689947749
BEDOK GREEN PRIMARY SCHOOL: success via postal_code | lat=1.323445932879926, lon=103.937878976352
ANCHOR GREEN PRIMARY SCHOOL: success via postal_code | lat=1.390369986546132, lon=103.8871653759329
BEACON PRIMARY SCHOOL: success via postal_code | lat=1.383949362118238, lon=103.7736320229752
SENG KANG PRIMARY SCHOOL: success via postal_code | lat=1.389250447782248, lon=103.8995278792292
FIRST TOA PAYOH PRIMARY SCHOOL: success via postal_code | lat=1.34032299499939, lon=103.8555299061816
LIANHUA PRIMARY SCHOOL: success via postal_code | lat=1.354241911272948, lon=103.7541658287112
XINGHUA PRIMARY SCHOOL: success via postal_code | lat=1.35799653782465, lon=103.8902163554591
JURONG PRIMARY SCHOOL: success via postal_code | lat=1.348438596989479, lon=103.7331565668572
DAZHONG PRIMARY SCHOOL: success via postal_code | lat=1.359179744727699, lon=103.7484721078394
EAST SPRING PRIMARY SCHOOL: success via postal_code | lat=1.352684007463578, lon=103.9616768491645
YUMIN PRIMARY SCHOOL: success via postal_code | lat=1.351315698908628, lon=103.9505510913724
MERIDIAN PRIMARY SCHOOL: success via postal_code | lat=1.375506770548346, lon=103.9349532761547
NEW TOWN PRIMARY SCHOOL: success via postal_code | lat=1.299811388840579, lon=103.7999648198951
KRANJI PRIMARY SCHOOL: success via postal_code | lat=1.393560504971042, lon=103.7473627209389
CANTONMENT PRIMARY SCHOOL: success via postal_code | lat=1.275472526232034, lon=103.8399626317482
BLANGAH RISE PRIMARY SCHOOL: success via postal_code | lat=1.276120479240372, lon=103.808628535239
CONCORD PRIMARY SCHOOL: success via postal_code | lat=1.380265161114646, lon=103.7365542956354
MARYMOUNT CONVENT SCHOOL: success via postal_code | lat=1.340438406613688, lon=103.8398117367746
CHANGKAT PRIMARY SCHOOL: success via postal_code | lat=1.340231639516331, lon=103.9520801140343
AHMAD IBRAHIM PRIMARY SCHOOL: success via postal_code | lat=1.433152715435181, lon=103.8329424010853
SI LING PRIMARY SCHOOL: success via postal_code | lat=1.432409357325257, lon=103.786035065192
PALM VIEW PRIMARY SCHOOL: success via postal_code | lat=1.383769230221237, lon=103.891354675017
TECK WHYE PRIMARY SCHOOL: success via postal_code | lat=1.383886604693974, lon=103.7539245585862
EDGEFIELD PRIMARY SCHOOL: success via postal_code | lat=1.400091395109958, lon=103.9078475991141
ZHONGHUA PRIMARY SCHOOL: success via postal_code | lat=1.360260724760189, lon=103.8697125173825
PIONEER PRIMARY SCHOOL: success via postal_code | lat=1.354425929307369, lon=103.7327909201966
BENDEMEER PRIMARY SCHOOL: success via postal_code | lat=1.321812507804748, lon=103.8654041676288
NORTHOAKS PRIMARY SCHOOL: success via postal_code | lat=1.457328673020936, lon=103.8140756111743
Done.

In [150]:
# verify schools have valid geocode
print(schools_gdf[schools_gdf["geocode_status"] != "success"])

# reproject from geographic CRS (WGS84) to a projected CRS using EPSG:3414 (SVY21)
schools_gdf = gpd.GeoDataFrame(
    schools_gdf,
    geometry=gpd.points_from_xy(schools_gdf["longitude"], schools_gdf["latitude"]),
    crs="EPSG:4326"
)
schools_gdf = schools_gdf.to_crs(epsg=3414)

Empty GeoDataFrame
Columns: [school_name, address, postal_code, nature_code, sap_ind, autonomous_ind, gifted_ind, P1_demand, P2A_demand, P2B_demand, P2C_demand, P2CS_demand, subject_count, distprog_count, cca_clubs, cca_others, cca_sports, cca_uniformed, cca_arts, affiliation_count, top_psle_score, school_score_raw, school_score, school_tier, latitude, longitude, searchval, formatted_address, postal_found, geocode_status, matched_query, geometry]
Index: []

[0 rows x 32 columns]

### 3. Get feature variables of schools

3.1 
- num_schools_1km
- num_schools_2km

In [144]:
# get unique hdb locations
unique_hdb = resale_gdf.drop_duplicates(subset=["postal_code"]).copy()
key_col = "postal_code"

# prepare unique hdb and school coordinates for distance calculation
school_coords = np.array([(geom.x, geom.y) for geom in schools_gdf.geometry])
hdb_coords = np.array([(geom.x, geom.y) for geom in unique_hdb.geometry])

school_names = schools_gdf["school_name"].tolist()

# build cKDTree for efficient spatial queries
tree = cKDTree(school_coords)

# get schools within 1km and 2km
indices_1km = tree.query_ball_point(hdb_coords, r=1000)
indices_2km = tree.query_ball_point(hdb_coords, r=2000)

# convert index arrays into school name lists
unique_hdb["schools_within_1km"] = [
    [school_names[i] for i in idx_list] for idx_list in indices_1km]

unique_hdb["schools_within_2km"] = [
    [school_names[i] for i in idx_list] for idx_list in indices_2km]

# count columns
unique_hdb["num_schools_1km"] = unique_hdb["schools_within_1km"].apply(len)
unique_hdb["num_schools_2km"] = unique_hdb["schools_within_2km"].apply(len)

3.2 
- num_tier1_schools_1km
- num_tier1_schools_2km

In [145]:
tier1 = schools_gdf[schools_gdf["school_tier"] == "Tier 1"].copy()
tier1_coords = np.array([(geom.x, geom.y) for geom in tier1.geometry])
tier1_names = tier1["school_name"].tolist()

tier1_tree = cKDTree(tier1_coords)

tier1_idx_1km = tier1_tree.query_ball_point(hdb_coords, r=1000)
tier1_idx_2km = tier1_tree.query_ball_point(hdb_coords, r=2000)

unique_hdb["tier1_schools_within_1km"] = [
    [tier1_names[i] for i in idx_list] for idx_list in tier1_idx_1km]

unique_hdb["tier1_schools_within_2km"] = [
    [tier1_names[i] for i in idx_list] for idx_list in tier1_idx_2km]

unique_hdb["num_tier1_schools_1km"] = unique_hdb["tier1_schools_within_1km"].apply(len)
unique_hdb["num_tier1_schools_2km"] = unique_hdb["tier1_schools_within_2km"].apply(len)

3.3
- num_tier2_schools_1km
- num_tier2_schools_2km

In [146]:
tier2 = schools_gdf[schools_gdf["school_tier"] == "Tier 2"].copy()
tier2_coords = np.array([(geom.x, geom.y) for geom in tier2.geometry])
tier2_names = tier2["school_name"].tolist()

tier2_tree = cKDTree(tier2_coords)

tier2_idx_1km = tier2_tree.query_ball_point(hdb_coords, r=1000)
tier2_idx_2km = tier2_tree.query_ball_point(hdb_coords, r=2000)

unique_hdb["tier2_schools_within_1km"] = [
    [tier2_names[i] for i in idx_list] for idx_list in tier2_idx_1km]

unique_hdb["tier2_schools_within_2km"] = [
    [tier2_names[i] for i in idx_list] for idx_list in tier2_idx_2km]

unique_hdb["num_tier2_schools_1km"] = unique_hdb["tier2_schools_within_1km"].apply(len)
unique_hdb["num_tier2_schools_2km"] = unique_hdb["tier2_schools_within_2km"].apply(len)

In [156]:
# merge back to full resale dataset if needed
school_feature_test = unique_hdb[[
    "postal_code",
    "num_schools_1km",
    "schools_within_1km",
    "num_schools_2km",
    "schools_within_2km",
    "num_tier1_schools_1km",
    "num_tier1_schools_2km",
    "num_tier2_schools_1km",
    "num_tier2_schools_2km"
]].copy()

resale_with_school_test = resale_gdf.merge(
    school_feature_test,
    on="postal_code",
    how="left"
)

resale_with_school_test.to_csv("resale_with_school_test.csv", index=False)

In [ ]:
# merge back to full resale dataset if needed
school_features = unique_hdb[[
    "postal_code",
    "num_schools_1km",
    "num_schools_2km",
    "num_tier1_schools_1km",
    "num_tier1_schools_2km",
    "num_tier2_schools_1km",
    "num_tier2_schools_2km"
]].copy()

resale_with_school = resale_gdf.merge(
    school_features,
    on="postal_code",
    how="left"
)
resale_with_school.head(5)

### 4. Check data integrity

In [ ]:
# define logical conditions to check for data integrity
mask = (
    (resale_with_school['num_tier1_schools_1km'] > resale_with_school['num_schools_1km']) |
    (resale_with_school['num_tier1_schools_2km'] > resale_with_school['num_schools_2km']) |
    (resale_with_school['num_tier2_schools_1km'] > resale_with_school['num_schools_1km']) |
    (resale_with_school['num_tier2_schools_2km'] > resale_with_school['num_schools_2km'])
)

# check if any row returned True for the errors
if mask.any():
    error_count = mask.sum()
    raise ValueError(f"Data Integrity Error: {error_count} records have tier counts exceeding total school counts.")
else:
    resale_with_school.to_csv("resale_with_school.csv", index=False)
    print("Validation passed. File saved successfully.")

Validation passed. File saved successfully.